### ISSUE TITLE
Problem with Animated Object

### ISSUE THREAD

**Issue by Sl11ck** [RandomiaGaming/Unity2DPixelPerfectCollider#2]
So I was gonna use this thing with an Animated Object and use the Recording Mode to sync diffrent colliders to diffrent frames and when I pressed **Regenerate Collider** it made the collider a box which was like 1/2 the charcters length diagonally upwards from him. Is this happening because this is an Animated Object?(If yes you should make it so it supports Animated Objects)

**Comment by FinlayTheBerry** [comment]
Thanks for raising an issue.  The script just regenerates a collider based on whatever sprite is in the sprite renderer so depending on how you animate the character and where the polygon collider and sprite renderer are you might have some problems i don't know.  I never tested this script with animations because changing the collider during game play can cause clipping and out of bounds glitches.  I would recommend making a child gameobject for each frame of the animation and then adding the required collider and sprite to that child.  Then have the animator just enable and disable the children gameobjects?  Not sure if you provide more details on what you want im happy to code a fix.  Thanks again for the comment

**Comment by Soul-Plays** [comment]
The thing is there is a sprite in the sprite renderer and even when I remove the animator component the problem persists, should I maybe send you the project file to see what is wrong with it?(Also I didnt know how do you send this with the tag but you should make the Pixel Perfect Collider 2D for tilemaps. The tilemaps have the custom outline shape and custom physics shape which are similar to the Polygon collider(And Im saying you should also do the custom outline so people could have for exampled coloured backround is there sprite sheets))

**Comment by Sl11ck** [comment]
The thing is there is a sprite in the sprite renderer and even when I remove the animator component the problem persists, should I maybe send you the project file to see what is wrong with it?(Also I didnt know how do you send this with the tag but you should make the Pixel Perfect Collider 2D for tilemaps. The tilemaps have the custom outline shape and custom physics shape which are similar to the Polygon collider(And Im saying you should also do the custom outline so people could have for exampled coloured backround in there sprite sheets))

**Comment by FinlayTheBerry** [comment]
Great idea i would love to make a version of this for tilemaps.  and as for animation the problem likely is that the animator component changes the sprite of the spriterenderer but the pixelcollider only regenerates when you press the button or call the Regenerate method.  Maybe I should add an option to check every frame and see if the collider needs to be regenerated.  Ill get to work on that.  Let me know if you have any other ideas.

**Comment by Sl11ck** [comment]
Ok cause for like the Pixel Perfect Collider 2D you can add a major improvement to it to make it work with multiple things. The improvement would include a drop down menu which you could choose what the script would affect. So something like this:

```
public enum ColliderType { Auto, Animated, Normal, Tilemap }
public ColliderType colliderType;
```
The Auto feature would try to detect what object you attached the script too via detecting the components
The Animated feature would detect every frame then set the collider for thoose(if you cant it would just be a fix for my problem)
The Normal would just be your script
The Tilemap would change the custom physics shape of the object

Then I also would imagine that you would have a tickbox that would appear when you choose tilemaps which would be Remove Colored backrounds or something like that which when you press it two options apear. The first one is amount and you can make the max five for example and then the others would be the colours and it would remove colors from the tilemaps. Also it would pick the sprites automatically the same way you did the Custom Physiscs Shape.

Also thx for even just reading this msg and thx a lot more if you actually do this.

**Comment by FinlayTheBerry** [comment]
Ok im on it!
